### PR TITLE
Validation Categorization and Sequence/ Directives updated to handle validation

### PR DESCRIPTION
**Pull request by jsons**
Andrew wanted you to review before I check in all my changes for validation.
Validation for Phenotypes Categorization and Sequence.  Both directives for single and multiple drop zones have validation.  After clicking save if a drop zone does not have a concept it will display an error.

Also, please provide IDE's format settings so I can correct.

### CODE REVIEW

**Comment by arpost** [comment]
Some comments:

1. I'd like the validation code to be entirely contained within the drop zone directives. They should work the same way as any other form field with respect to validation.
2. Angular has built-in validation properties. Is there a reason why you are not using them?
3. I don't think the conceptEnableValidation, enableValidation etc. properties should be necessary, if you are using the built-in validation properties. Regular form fields "just work" if validation is turned on at the form level, and I want the same behavior for the drop zone directives.
4. I believe there are existing bootstrap classes you can use to achieve the color change when there is a validation error, such as http://getbootstrap.com/css/#forms-control-validation.

**Comment by arpost** [comment]
If enableValidation=true means that the field is required, then just make the property name "required".

**Comment by jsons** [comment]
@arpost  I can use Angular built in validation for the various drop downs and check boxes.  Basically anything that has a basic html form element.

Approaching validation for the tree component drop area was a little tricky.  If a phenotype or context is not listed in the drop zone/area and the user selects save it will highlight the drop zone without saving.  Being that the tree component is not a form component(select, checkbox, input), I had to figure out a way to add validation.  I may have over thought it, but I will go back and explore if you are referring to the tree component/ drop zone.  

Also, if you have a better approach for the tree component/ drop zone validation  let me know.   I will go back to the drawing board with a better design :-) Thanks

**Comment by jsons** [comment]
@arpost  I came up with another pattern that is contained to the directive.  so the only property you would need for the directive to work is ng-model and required keyword(which operates similar to the require param for any other input field in a form.)  I also reverted all my changes to the other files.  Take a look at this commit: https://github.com/eurekaclinical/eurekaclinical-analytics-webclient/pull/3/commits/fd489e4fa80b3565b68c76221731449c4fc315e5
It is how Angular is doing its validation under the covers.  This is my first pass, which I will make it better.

**Comment by jsons** [comment]
Closing this Pull Request.  Will resubmit a new one with concise changes so that it is easy to review.

**Pull request closed without merging**
